export const STORAGE_KEYS = {
    TICKET: 'TICKET',
    EVENT: 'EVENT',
    EVENT_ID: 'EVENT_ID',
    TICKET_TYPE: 'TICKET_TYPE',
    USER_ID: 'USER_ID',
    token: 'token',
    refreshToken: 'refreshToken',
    EVENT_DETAILS: 'EVENT_DETAILS',
    ACTIVE_TICKET: 'ACTIVE_TICKET',
    TICKET_COUNT: 'TICKET_COUNT',
    USER_DETAILS: 'USER_DETAILS',
    QUANTITY: 'Quantity',
    CURRENT_STEP: 'Current_Step',
    DONATION_AMOUNT: 'Donation_amount',
    PRODUCT: 'Product',
    PRODUCT_QUANTITY: 'Product_Quantity',
    ADDRESS: 'Address',
    GOOGLE_AUTH: 'GOOGLE_AUTH',
}