import { IUser } from "./user" 

export type IDonation = {
    creatorID: string,
    name: string,
    bannerImage: string,
    description: string,
    goal: any,
    total?: number,
    visibility: "PUBLIC" | "PRIVATE" | null,
    collaborators?: Array<string>,
    purpose: string,
    funnelID?: string,
    funnelType?: "EVENT" | "COMMUNITY" | null,
    endDate: any,
    fundRaiserGroupId?: string
}

export type IDonationList = {
    creatorID: string,
    name: string,
    bannerImage: string,
    description: string,
    goal: number,
    total: number,
    visibility: "PUBLIC" | "PRIVATE" | null,
    collaborators: Array<string>,
    purpose: string,
    funnelID?: string,
    funnelType: "EVENT",
    endDate: any, 
    createdBy: IUser,
    createdDate: number,
    fundRaisers: any,
    fundRasingGroupId: IDonationGroupData,
    id: string,
    isDeleted: boolean,
    lastModifiedBy: any,
    lastModifiedDate: any,
    returnMessage: string,
    status: any,
    statusCode: number,
    totalInGroup: number,
    user: IUser,
    isCollaborator: boolean
}

export type IDonationGroup ={
    "id": string,
    "createdDate": 1732026328019,
    "lastModifiedBy": string | any,
    "createdBy": string | any,
    "lastModifiedDate": number,
    "isDeleted": boolean,
    "status": number,
    "statusCode": number,
    "returnMessage": string,
    "user": IUser,
    "name": string,
    "description": string,
    "bannerImage": string,
    "fundRaisers": Array<IDonationList>,
    "expirationDate": string | any,
    "fundRasingGroupId": string | any,
    "goal": string | any,
    "total": string | any,
    "visibility": string | any,
    "collaborators": string | any,
    "purpose": string | any,
    "funnelID": string | any,
    "funnelType": string | any,
    "endDate": string | any,
    "isCollaborator": string | any,
    "totalInGroup": string | any
  }

export type IDonationGroupData = {
    id: string,
    createdDate: any,
    createdAt: any,
    lastModifiedBy: string | any,
    createdBy: string,
    lastModifiedDate: any,
    isDeleted: boolean,
    status: "ACTIVE",
    creatorID: string,
    name: string,
    bannerImage: string,
    description: string,
} 